made Pylint implementation similar to Eslint

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,22 +1,38 @@
 #!/bin/bash
 cd "$(git rev-parse --show-toplevel)"
+# Pylint Path is Micky's local path, feel free to change in PR 
+PYLINT = "c:\users\micky\appdata\local\programs\python\python310\lib\site-packages" 
 ESLINT="client/node_modules/.bin/eslint"
 pwd
 
-staged=`git diff --name-only --cached --diff-filter=A --diff-filter=M | cat`
-pylint="c:\users\micky\appdata\local\programs\python\python310\lib\site-packages  --rcfile .pylintrc --load-plugins pylint_django --load-plugins pylint_quotes --reports=no"
+if [[ ! -x "$PYLINT" ]]; then
+	  printf "\t\033[41mPlease install Pylint\033[0m (pip install pylint)\n"
+	    exit 1
+    fi
 
-if [ "$staged" ]
-then
-  target=`cat "$staged" | grep '.py$'`
-else
-  target=`git diff --name-only | cat | grep '.py'`
-fi
+    STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".py\{0,1\}$"))
 
-if [ "$target" ]
-then
-  $pylint "$target"
-fi
+    echo "Checking ${#STAGED_FILES[@]} staged files for Pylint Errors..."
+
+    if [[ "$STAGED_FILES" = "" ]]; then
+	      exit 0
+      fi
+
+      $PYLINT "${STAGED_FILES[@]}" --fix
+
+      PYLINT_EXIT="$?"
+
+      # Re-add files since they may have been fixed
+      git add "${STAGED_FILES[@]}"
+
+      if [[ "${PYLINT_EXIT}" == 0 ]]; then
+	        printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
+	else
+		  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix pylint errors and try again\n"
+		    exit 1
+	    fi
+
+	    exit $?
 
 if [[ ! -x "$ESLINT" ]]; then
 	  printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
