Fix pre-commit script indentation

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,31 +3,32 @@ cd "$(git rev-parse --show-toplevel)"
 ESLINT="client/node_modules/.bin/eslint"
 pwd
 
+# ESLint precommit logic
 if [[ ! -x "$ESLINT" ]]; then
-	  printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
-	    exit 1
-    fi
+  printf "\t\033[41mPlease install ESlint\033[0m (npm install eslint)\n"
+  exit 1
+fi
 
-    STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$"))
+STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$"))
 
-    echo "Checking ${#STAGED_FILES[@]} staged files for ESLint Errors..."
+echo "Checking ${#STAGED_FILES[@]} staged files for ESLint Errors..."
 
-    if [[ "$STAGED_FILES" = "" ]]; then
-	      exit 0
-      fi
+if [[ "$STAGED_FILES" = "" ]]; then
+  exit 0
+fi
 
-      $ESLINT "${STAGED_FILES[@]}" --fix
+$ESLINT "${STAGED_FILES[@]}" --fix
 
-      ESLINT_EXIT="$?"
+ESLINT_EXIT="$?"
 
-      # Re-add files since they may have been fixed
-      git add "${STAGED_FILES[@]}"
+# Re-add files since they may have been fixed
+git add "${STAGED_FILES[@]}"
 
-      if [[ "${ESLINT_EXIT}" == 0 ]]; then
-	        printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
-	else
-		  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
-		    exit 1
-	    fi
+if [[ "${ESLINT_EXIT}" == 0 ]]; then
+  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
+else
+  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
+  exit 1
+fi
 
-	    exit $?
+exit $?
